name: ScrollTeleportation
version: '1.0.5'
main: org.clockworx.scrollteleportation.ScrollTeleportation
api-version: '1.21'
authors: [ClockWorX LLC, Rick Dawson]
description: A modern RPG-like teleportation system using paperscrolls
website: https://github.com/radawson/ScrollTeleportation

permissions:
  # User permissions - Basic functionality for regular players
  scrollteleportation.user:
    description: Basic user permissions for ScrollTeleportation
    default: true
    children:
      scrollteleportation.teleport: true
      scrollteleportation.use: true
      scrollteleportation.view: true

  # Admin permissions - Full control over the plugin
  scrollteleportation.admin:
    description: Administrative permissions for ScrollTeleportation
    default: op
    children:
      scrollteleportation.user: true
      scrollteleportation.give: true
      scrollteleportation.walkbypass: true
      scrollteleportation.invbypass: true
      scrollteleportation.delaybypass: true
      scrollteleportation.usesbypass: true
      scrollteleportation.potioneffectbypass: true
      scrollteleportation.set: true
      scrollteleportation.create: true
      scrollteleportation.reload: true

  # Individual permissions
  scrollteleportation.teleport:
    description: Allows a player to use scrolls
    default: true
  scrollteleportation.use:
    description: Allows a player to use scrolls
    default: true
  scrollteleportation.view:
    description: Allows a player to view scroll information
    default: true
  scrollteleportation.give:
    description: Allows a player to give scrolls
    default: op
  scrollteleportation.walkbypass:
    description: Players with this permission can walk while teleports are being cast
    default: op
  scrollteleportation.invbypass:
    description: Players with this permission can open inventories while teleports are being cast
    default: op
  scrollteleportation.delaybypass:
    description: Players with this permission can bypass delays
    default: op
  scrollteleportation.usesbypass:
    description: Players with this permission can bypass the use counter
    default: op    
  scrollteleportation.potioneffectbypass:
    description: Players with this permission can bypass potion effects
    default: op
  scrollteleportation.set:
    description: Allows a player to set scroll variables
    default: op
  scrollteleportation.create:
    description: Allows a player to create scrolls
    default: op
  scrollteleportation.reload:
    description: Allows a player to reload config files
    default: op          

commands:
  scrolltp:
    description: Main command for Scroll Teleportation
    usage: /<command> [subcommand]
    aliases: [stp, scrollteleport] 